# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.hostname = "cluster-101"
  if File.exists?(".vagrant/machines/default/libvirt/action_provision")
    config.vm.synced_folder "/home/tmalsbar/multicloud-k8s", "/vagrant"
  else
    # hold off on the sync
  end
  config.vm.provider :libvirt do |libvirt|
    libvirt.graphics_ip = '0.0.0.0'
    # add random suffix to allow running multiple jobs
    libvirt.random_hostname = 'yes'
    libvirt.cpus = 16
    libvirt.cpuset = '44-65'
    libvirt.memory = 32768
    libvirt.machine_virtual_size = 400
  end
  config.vm.provision "net", type: "shell", path: "fix.generic-ubuntu-dns.sh", privileged: true
end
