kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sriov-network-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sriov-network-operator
subjects:
- kind: ServiceAccount
  name: sriov-network-operator
  namespace: {{ .Release.Namespace }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sriov-network-config-daemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sriov-network-config-daemon
subjects:
- kind: ServiceAccount
  name: sriov-network-config-daemon
  namespace: {{ .Release.Namespace }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-webhook-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operator-webhook-sa
subjects:
- kind: ServiceAccount
  name: operator-webhook-sa
  namespace: {{ .Release.Namespace }}
