apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-qat-kernel-plugin
  labels:
    app: intel-qat-kernel-plugin
spec:
  selector:
    matchLabels:
      app: intel-qat-kernel-plugin
  template:
    metadata:
      labels:
        app: intel-qat-kernel-plugin
    spec:
      hostPID: true
      initContainers:
      - image: malsbat/qat-driver-installer:latest
        imagePullPolicy: IfNotPresent
        name: qat-driver-installer
        securityContext:
          privileged: true
        env:
          - name: QAT_INSTALL_DIR_HOST
            value: /opt/qat
          - name: QAT_INSTALL_DIR_CONTAINER
            value: /usr/local/qat
        volumeMounts:
        - name: root-mount
          mountPath: /root
        - name: qat-install-dir
          mountPath: /usr/local/qat
      containers:
      - name: intel-qat-kernel-plugin
        securityContext:
          readOnlyRootFilesystem: true
          privileged: true
        image: integratedcloudnative/intel-qat-plugin:0.15.0
        imagePullPolicy: IfNotPresent
        args: ["-mode", "kernel"]
        volumeMounts:
        - name: devfs
          mountPath: /dev
        - name: etcdir
          mountPath: /etc
          readOnly: true
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: etcdir
        hostPath:
          path: /etc
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: devfs
        hostPath:
          path: /dev
      - name: root-mount
        hostPath:
          path: /
      - name: qat-install-dir
        hostPath:
          path: /opt/qat
