{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "intel-device-plugins.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "intel-device-plugins.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "intel-device-plugins.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ $.Release.Namespace }}
{{- end }}
