apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:default:privileged
  namespace: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:privileged
subjects:
- kind: ServiceAccount
  name: default
  namespace: operator
- kind: ServiceAccount
  name: k8s-nfn-sa
  namespace: operator
