apiVersion: v1
kind: Service
metadata:
  name: nfn-operator
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    name: nfn-operator
